### ISSUE TITLE
Enhancements to the two column editor page

### ISSUE THREAD

**Issue by thanhduc-epi** [episerver/Foundation#111]
Suggestions:
Move "Left column" and "Right column" properties to a new tab called "Layout"
Rename "Left column" and "Right column" properties to "Left column width" and "Right column width"	
Use a selection factory to select the values instead of an int value. Suggested values for the selection factory are (use appropriate values so the column widths are set appropriately):
Half (1/2)	
One third (1/3)	
Two thirds (2/3)
One quarter (1/4)	
Three quarters (3/4)	
One sixth (1/6)	
Five sixths (5/6)	
Then all of 1,2,3,4,5,6,7,8,9,10,11 to allow for custom settings
Ensure that the left/right columns become full width when displaying on mobile (use bootstrap widths)

**Comment by ngocnguyen-epi** [comment]
Won't fix.
