### ISSUE TITLE
Issues relate to Instore Pickup

### ISSUE THREAD

**Issue by tanvu-epi** [episerver/Foundation#138]
**Default selected instore pickup at product detail page does not work**
1. Go to product detail page
2. Select Instore pickup option => user will see a pickup store is selected
3. Add item to cart
==> Expected: Item is added to cart as pickup at the selected store
==> Actual: Item is added to cart but with delivery method. User need to choose another store then choose a first selected store again to pick correctly store. So it will not work if a market has only one store pickup. 

**Shipment can be blank when checking out one item with both delivery and instore pickup**
1. Go to product detail page 
2. Add item as delivery to cart 
3. Select in store pickup 
4. Add item as store pick up to cart 
5. Go to checkout page 
6. Place an order 
=> Expected: Create two shipment , 1 item in delivery shipment, 1 item in instore pickup shipment 
=> Actual: Create two shipment but both 2 item in one delivery shipment, and blank item in in store pickup shipment

**Always use instore pickup for whole order if add the first item as instore pickup**
1. Go to product detail page
2. Add item as in store pick up
3. Add another item as delivery 
4. Go to checkout page
=> Expected: Separate order to two shipment, one for delivery, one for instore pickup 
=> Actual: Ignore shipping step and go to Billing, all items are added to one shipment use instore pickup shipping method.

**Comment by ngocnguyen-epi** [comment]
Fixed in #6
