### ISSUE TITLE
Cannot remove credit card in my account

### ISSUE THREAD

**Issue by thanhduc-epi** [episerver/Foundation#140]
**Describe the bug**
Cannot remove credit card in my account.

**To Reproduce**
Precondition: An exisitng customer has at least one credit card
1. Go to customer account
2. Select credit card tab
3. Remove an existing credit card
4. Redirect to http://foundation/en/my-account/credit-cards/Remove/?creditCardId=b5d7995c-499f-4fe4-96d6-214fd3f689ff with error "http://foundation/en/my-account/credit-cards/Remove/?creditCardId=b5d7995c-499f-4fe4-96d6-214fd3f689ff"

**Expected behavior**
Remove credit card successfully.

**Comment by vessokolev** [comment]
I experience the same problem - cannot remove the credit card information. Which means I will not use any longer Github to sponsor projects. The documentation here:

https://docs.github.com/en/enterprise-cloud@latest/billing/managing-your-github-billing-settings/adding-or-editing-a-payment-method

makes a false statement. In fact, there is not "Remove" link!

**Comment by bywangxp** [comment]
+1
