### ISSUE TITLE
Missing ClientResources/Scripts at mapping from mosey at module.config

### ISSUE THREAD

**Issue by FernandoFerreiraNunes** [episerver/Foundation#159]
Download the 0acf8f7 commit, and executed the build.cmd. After setting everything to run. was not able to create a page. 
The request was :

http://localhost:53396/episerver/Shell/11.22.0/ClientResources/mosey/contentediting/CreateContent.js

Dont now if is related. but after changing the module.config of cms site to : 
<?xml version="1.0" encoding="utf-8"?>
<module>
  <dojo>
    
    <paths>
      <add name="foundation" path="ClientResources/Scripts" />
    </paths>
  </dojo>

before is: path="Scripts" only.

Now i am able to create pages

**Comment by lunchin** [comment]
I am not sure I understand what the issue is.  Also are you using iisexpress instead of the iis site that was created?

**Comment by lunchin** [comment]
I am not sure I understand what the issue is.  Also are you using iisexpress instead of the iis site that was created?

**Comment by FernandoFerreiraNunes** [comment]
Hi Mark,

Using code from commit 0acf8f7<https://github.com/episerver/Foundation/commit/0acf8f702f0bdc907db770859067681ee11ea98b>
To create the first page to set as start page. The page to create a new page was not presented.


[cid:image002.png@01D5941E.F71EAC90]

Found the error 404

[cid:image003.png@01D5941E.F71EAC90]

After a search, I got the module.config with path to “Scripts”,

[cid:image001.png@01D5941E.F71EAC90]

Decided to set path to “ClientResources/Scripts”:

[cid:image004.png@01D5941E.F71EAC90]


At the new page is fixed: is this related?

[cid:image005.png@01D5941F.C8AC9BF0]

Best Regards,
Fernando Nunes

**Comment by lunchin** [comment]
Was  just wondering about IIS express did not know if that caused the issue.  I am able to add pages on the latest so not sure how to recreate.

**Comment by FernandoFerreiraNunes** [comment]
on the email you saw the images? going to test it with same steps on iis

**Comment by FernandoFerreiraNunes** [comment]
Using IIS the issue does not appear, but with IISExpress the "New page" page does not appear

**Comment by FernandoFerreiraNunes** [comment]
shall i close the issue?

**Comment by lunchin** [comment]
Leave it open, will see if changing makes it work for both.
