### ISSUE TITLE
Issue Management Board Nominations

### ISSUE THREAD

**Issue by lunchin** [episerver/Foundation#177]
This board will be responsible for managing the different issues related to the project.  This means ensuring that bug-fix and feature requests have the necessary information required to be completed.  

If you are interested in becoming a member of  the board please leave a comment on why you would like to be involved.   The deadline for all nominations will be 11/30/2019.

The board will have a few basic rules to start
- One Episerver employee must be a member of the board
- Maximum of 5 members to start
- Board members will self govern on all matters related to the board
- Episerver reserves the right to veto any decision that negatively affects Episerver

**Comment by shgreig-mtm** [comment]
I am interested in being a issue management board member, I have been an episerver dev for a while now across the full product suite working on multiple sites.

**Comment by eddingeldein** [comment]
I am interested in being an issue management board member.  I am currently serving as the product manager for my company's B2B Epi accelerator. I work with our internal steering committee to determine the overall roadmap, working with our developers to identify and resolve bugs. I research and review the market and our own internal projects to determine the best designs for requested features to support our clients' needs.

Serving on this board will help me get familiar with Foundation and identify how my company can best use the product. In turn, I can provide insight from my company's experiences to help the board address challenges the Foundation team faces going forward.  Thank you.

**Comment by EricHerlitz** [comment]
Sign me up if there's room

**Comment by valdisiljuconoks** [comment]
+1 here

**Comment by lunchin** [comment]
Please send me your preferred contact email information so we can move this offline.
mark.hall @ episerver
