### ISSUE TITLE
Code Review Board Nominations

### ISSUE THREAD

**Issue by lunchin** [episerver/Foundation#178]
This board will be responsible for reviewing and testing all pull requests to ensure the quality and  correctness of the code..

If you are interested in becoming a member of the board please leave a comment on why you would like to be involved. The deadline for all nominations will be 11/30/2019.

The board will have a few basic rules to start
- One Episerver employee must be a member of the board
- Maximum of 5 members to start
- Board members will self govern on all matters related to the board
- Episerver reserves the right to veto any decision that negatively affects Episerver

**Comment by shgreig-mtm** [comment]
I am interested in being a review board member, I have been an episerver dev for a while now across the full product suite working on multiple sites.

**Comment by bbsdddougla** [comment]
I'm interested in being a code review board member, too. 

* I've been a part of discovery, specc'ing, and implementation on multiple ecommerce projects covering a range of epi technologies
* I review code and features from other devs (internal and external) as a part of my job
* I've been a part of a team working on our internal starter kit for epi, which we've used for several successful ecommerce projects
* I'm interested in developing code style and architecture guidelines as a part of a team
* I have some opinions about using DI (mostly based around [Mark Seeman's examples as laid out in his DIPPP book](https://www.manning.com/books/dependency-injection-principles-practices-patterns))
* I'm eager to see what ideas other Epi devs have about best practices for using the framework and organizing code for maintainability and ease of extension.

Note that most of my contributions for work have been committed to our internal git repo, so my github history is a little light. Part of my reason for wanting to be on the board is to increase my contributions to open-source software, both by writing and reviewing code.

**Comment by EricHerlitz** [comment]
Sign me up if there's room

**Comment by valdisiljuconoks** [comment]
+1 here

**Comment by lunchin** [comment]
Please send me your preferred contact email information so we can move this offline.
mark.hall @ episerver
