### ISSUE TITLE
Implement Open Graph tags on Foundation pages

### ISSUE THREAD

**Issue by ngocnguyen-epi** [episerver/Foundation#180]
Using Open Graph tags can help with SEO and also really help with social sharing. Please implement open graph tags on Foundation pages, see https://ogp.me/

Suggested mapping / usage as follows:

Tag | Primary mapping (if available and entered) | Fallback to use if primary not available | Fallback to use if fallback1 not present | Note
-- | -- | -- | -- | --
og:title | EntryContentBase.DisplayName | CurrentContent.Name |   |  
og:description | FoundationPageData.PageDescription |   |   |  
og:image | FoundationPageData.PageImage |   |   | Please ensure that the URL is a fully qualified URL with domain etc  https://www.mydomain.com/image1.png
og:type | "article" unless it’s the homepage in which case use "website" |   |   | See https://ogp.me/#types for appropriate type usage
NOTE: Article tags should only be rendered for content pages, not listing pages etc |   |   |   |  
article:content_type | (new property on meta data tab) CurrentContent.ContentType | [ContentType(DisplayName)] |   | See https://ogp.me/#types for appropriate type usage
article:tag | LocationItemPage.Tags |   |   | See https://ogp.me/#types for appropriate type usage
article:category | LocationItemPage.Continent, LocationItemPage.Country | EntryContentBase.Categories | CurrentContent.Categories | See https://ogp.me/#types for appropriate type usage
article:industry | (new property on meta data tab) CurrentContent.Industry |   |   | See https://ogp.me/#types for appropriate type usage
article:author | (new property on meta data tab) CurrentContent.Author |   |   | See https://ogp.me/#types for appropriate type usage
article:published_time | standard start publish date |   |   | See https://ogp.me/#types for appropriate type usage
article:modified_time | standard modified date |   |   | See https://ogp.me/#types for appropriate type usage
article:expiration_time | standard end publish (if present) |   |   | See https://ogp.me/#types for appropriate type usage

**Only render the tag if the content/fallback has been entered for it, do not render empty tags.**

**Comment by jstemerdink** [comment]
I use this [library](https://www.nuget.org/packages/Boilerplate.Web.Mvc5/) which takes care of all the plumbing for OpenGraph tags and Twitter cards
