### ISSUE TITLE
setup.cmd doesn't handle whitespaces in the paths

### ISSUE THREAD

**Issue by alasvant** [episerver/Foundation#201]
setup.cmd doesn't handle whitespaces in the paths.
If you get the sources to a location where there are whitespaces in the path like 'c:\my folder\with whitespaces\' the setup.cmd script will fail because it doesn't use double quotes in the path related script variables.

Behavior observed on Windows 10.

**To Reproduce**
1. Download the Foundation project as zip file from GitHub
2. Extract the downloaded zip file to path that contains whitespaces, for example: 'c:\episerver foundation demo\'
3. Open command prompt with elevated privileges
4. Change directory to this folder you extracted the zip and change directory to the that contains the setup.cmd
5. Execute the setup.cmd

**Expected behavior**
The Foundation is properly installed: NuGet packages are restored, node modules installed, solution is built, database(s) are created, etc

** Actual result **
Most of the tasks fail because the script doesn't properly handle the whitespaces in the directory paths.

Directory variable should be double quoted like this when used: "%ROOTPATH%\Foundation.sln"

Question that remains, do you want to fix this or want a PR? ;-)

** EDITED ** Originally this was about build.cmd but Mark Hall changed the script, build.cmd nowadays have different purpose and the old build.cmd is now setup.cmd

**Comment by trungdo-epi** [comment]
PRs are more than welcome.

**Comment by alasvant** [comment]
@trungdo-epi cannot assign this issue to myself but there is the pending PR now created.
