### ISSUE TITLE
Excluding Products and Projects - how hard?

### ISSUE THREAD

**Issue by LucGosso** [episerver/Foundation#214]
Detaching project in solutions seems not that easy as you may want it to be. From readme.md: "allowing developers to select Episerver products as projects to include or exclude"

Foundation.Campaign works to detach without compile errors

When i detach folowing project
Personalization x2
Demo
Social

I get 247 Errors, which makes me hesitating if it is a good idea to start removing "features", 247 Errors is without errors in views. 

1. What is your opinion on this? 
2. Will the site run after removing all "Features" such as rating, tracking?

3. If i leave the Tracking, where does it track? 
4. What is safe to remove?
5. Demo seems tight coupled to Commerce with coupon, is Demo detachable at all? 

I´m about to setup a commerce demo site for an addon partner and not convinced, if this is the right approach, or should i use quicksilver. 

thanks for taking your time figuring out...

**Comment by lunchin** [comment]
We are still working on the documentation on this but the basic premise i had on this is this.
If you don't have every product licensed then you have two options

Create a new visual studio template site
Add the projects to your solution a copy and paste of submodules
Add the features you want from the main Foundation project
Take ownership of code

Create a new visual studio template site
Add nuger packages to site

There is a pack.cmd that creates the nuget packages but they have not been verified yet as seen in the issues.  Also need to figure out if the nugget packages will reside on build server nugget feed of Episerver nugget feed.

Let me know if this helps.

**Comment by LucGosso** [comment]
What about Q3 and Q5? Any answers?

**Comment by lunchin** [comment]
You should be able to set enabletracking=false and not have to remove it all.  If you do remove it the site will still run fine. 

If you leave the tracking there is a foundation account it will track to.

**Comment by shella-cabatbat** [comment]
I quite agree with the original post. I tried to detach/exclude paid projects which are not part of the client's subscriptions.
While some detaches quite easily, e.g. Campaign.
Some are definitely not. 

Foundation.Social seems too tightly coupled with the User Identity features that if I remove it, I have to refactor and recreate all the user account pages. :(
