### ISSUE TITLE
404 on EPIServer.Insight.UI Link

### ISSUE THREAD

**Issue by mattcartwright** [episerver/Foundation#375]
When clicking on the EPIServer.Insight.UI link in the top right menu bar 

![image](https://user-images.githubusercontent.com/29631627/74447216-ef850f80-4e70-11ea-949a-0b0cf61242a9.png)

You get a 404.

Should it be going to something like http://webhelp.episerver.com/latest/en/personalization/insight/about-insight.htm?

If someone can give me the correct link I'll fix it and create a pull request.

Matt

**Comment by ngocnguyen-epi** [comment]
Episerver Add-on team will fix the issue.
