### ISSUE TITLE
Compiler Error Message: CS1519: Invalid token '=' in class, struct, or interface member declaration

### ISSUE THREAD

**Issue by daphonk** [episerver/Foundation#391]
Hi, I installed everything like it is in the HowTo. But if I went to the setup page I get this error:

CS1519: Invalid token '=' in class, struct, or interface member declaration
`
Line 44:     } Line 45:      Line 46:     public virtual EPiServer.Personalization.GuiSettings, EPiServer.Cms.AspNet EditTreeSettings { Line 47:         get { Line 48:             return ((EPiServer.Personalization.GuiSettings, EPiServer.Cms.AspNet)(this.GetPropertyValue("EditTreeSettings")));
--
`

`

c:\windows\system32\inetsrv> "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /t:library /utf8output /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /out:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\95ede20d\de815cd3\App_Code.46_b4m9g.dll" /D:DEBUG /debug+ /optimize- /w:4 /nowarn:1659;1699;1701;612;618 /warnaserror-  "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\95ede20d\de815cd3\App_Code.46_b4m9g.0.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\95ede20d\de815cd3\App_Code.46_b4m9g.1.cs"   Microsoft (R) Visual C# Compiler version 4.8.3752.0  for C# 5 Copyright (C) Microsoft Corporation. All rights reserved.    This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240
--

`

**Comment by lunchin** [comment]
This usually means the solution cannot build for some reason.  There should be a log file build\logs\build.txt that shows why it cannot build.

**Comment by daphonk** [comment]
Hi the build Log, is good until this line.


```

NuGet Config files used:
    E:\EpiServer\NuGet.Config
    C:\Users\mce\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    C:\Users\mce\.nuget\packages\
    https://api.nuget.org/v3/index.json
    https://nuget.episerver.com/feed/packages.svc/

Installed:
    200 package(s) to packages.config projects
## NPM Install 
## Gulp Install ## 			  
[[90m20:41:29[39m] Working directory changed to [35mE:\EpiServer\src\Foundation[39m
[[90m20:41:31[39m] Using gulpfile [35mE:\EpiServer\src\Foundation\Gulpfile.js[39m
[[90m20:41:31[39m] Starting '[36mdefault[39m'...
[[90m20:41:31[39m] Starting '[36msass[39m'...
[[90m20:41:31[39m] Starting '[36mjs[39m'...
[[90m20:41:32[39m] Finished '[36mjs[39m' after [35m851 ms[39m
[[90m20:41:37[39m] Finished '[36msass[39m' after [35m5.23 s[39m
[[90m20:41:37[39m] Finished '[36mdefault[39m' after [35m5.23 s[39m
## Clean and build ## 				 
## Cleaning packages folder ## 
## Set folder permissions ## 
0 Dateien erfolgreich verarbeitet, bei 1 Dateien ist ein Verarbeitungsfehler aufgetreten.
## Creating conectionstrings.config ## 
```

**Comment by daphonk** [comment]
I fixed up the permissionproblem manuelly, because of "Everyone"-group doesn't exists on a german Windows.

The error still exists, there are no further errors in the logfile.

**Comment by lunchin** [comment]
Can you try to rebuild the solution in visual studio?

**Comment by daphonk** [comment]
This issue can be closed. It was a outed version of msbuild, worked with VS build tools 2019
