### ISSUE TITLE
Add schema.org markup to improve search engine visibility

### ISSUE THREAD

**Issue by PaulGruffyddAmaze** [episerver/Foundation#409]
Schema.org is the result of a collaboration between Google, Microsoft, Yahoo and Yandex with the intention of providing semantic meaning within web content. It defines a vocabulary for describing entities and the relationships between them in a way that can be easily understood by computers. While applying schema markup to web pages may not directly result in an improvement in search rankings, it can change the way search results are presented, helping results to stand out from the crowd, leading to a higher click-through rate. See [Google's search gallery](https://developers.google.com/search/docs/guides/search-gallery) for more details.

Looking through Foundation, there are several entities defined which would map neatly to Schema.org types with little or no additional requirements of the editors, more specifically:
- Organization
- BlogPosting
- Product
- Location

The markup can be added in one of three flavours (RDFa, Microdata and JSON-LD) but google's preference is for JSON-LD so that's the approach we should take. This form of schema markup is also neatly separated from the markup of the page making it easier to add in a clean, extensible way independent of the UI. To assist with the mapping, the schema.org models have been made available as a nuget package called schema.net (though an older version needs to be used in order to avoid clashes in json.net versions).

A good level of SEO is an essential for any web project and, given that Foundation aims to showcase Episerver's capabilities and provide a base on which to build new greenfield projects, it seems sensible to me that we should include schema markup as part of that.

**Comment by PaulGruffyddAmaze** [comment]
I've put in a pull request for this, I just need to sort the license agreement.

**Comment by lunchin** [comment]
Thanks for the contribution, closing this as I just merged it.
