### ISSUE TITLE
advanced-cms-forms identified as trojan by F-secure

### ISSUE THREAD

**Issue by riqnevala** [episerver/Foundation#411]
Foundation master was recognized as https://www.f-secure.com/v-descs/trojan-downloader_w32_kavala.shtml by our company virus scanner F-secure.

This might be just a false positive, at the time I don't have the means to verify.

**To Reproduce**
1. Download Foundation master branch as a zip
2. Open and unzip to C:\
3. F-secure should raise a warning, quarantine and/or delete the file.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by kmukku** [comment]
@lunchin Why did you close this?

**Comment by riqnevala** [comment]
Exact path to the suspicious file is \Foundation\src\Foundation\modules\_protected\advanced-cms-forms\

Virus scanner interferes with the installation so this impacts development. I did send out a sample to F-secure for analysis and hopefully whitelisting.

**Comment by lunchin** [comment]
I don't now what fsecure is and the link looks suspect so I did not click on it.   There is nothing in those directories that is suspicious.

**Comment by riqnevala** [comment]
As I told in the first post, F-secure is a virus scanner. Virus scanners try to recognize malware by identifying their behaviour. 

Trojans usually write data on disk to infect, and send spam email to spread. I guess cms-form could do one or both of those actions. As the code in said package is not intended to be malware, it is called a false positive.

When virus scanner finds suspicious file, it quarantines the file by removing it from disk, and it will impact the installation of this git package. I have sent a sample to F-secure for analysis and they whitelisted it in their virus database, so other developers would not get false positives on their systems.

I opeden this issue just to inform developers about this scenario as it clearly affects the installation process (other virus scanners may still act similarly).
