### ISSUE TITLE
Settings pages

### ISSUE THREAD

**Issue by ngocnguyen-epi** [episerver/Foundation#441]
**Is your feature request related to a problem? Please describe.**
During discussion on Mosey Capital, we have identified that the current method of storing and accessing settings leads to a clutter on the home page, where site settings and content are mixed. To overcome this as well as to allow settings inheritance when creating multi-site setup, we have revived an old concept of settings pages.

[Settings Page.docx](https://github.com/episerver/Foundation/files/4357782/Settings.Page.docx)

**Comment by ngocnguyen-epi** [comment]
@tanvu-epi Updated settings page 
[Settings Page Updated.docx](https://github.com/episerver/Foundation/files/4401867/Settings.Page.Updated.docx)

**Comment by tanvu-epi** [comment]
@lunchin I have taken a look the first and second document. I see, by the first way (the first document), we need a page type for all settings of the site. And the second document (updated document), we will create some page type, each settings group (content reference, header, footer ...) correspond to each page type, right? Which the way will we implement? I think the first way is more suitable, I dont think need some page types to manage site settings.

**Comment by tanvu-epi** [comment]
@lunchin I have pushed code to feature/441-settings-page, implement the first way (1 page type), I keep the setting properties in home page types (cms, commerce, demo) but their value get from Settings Page and don't have setter. Because the project is using setting property directly from HomePage so much, so I do that to cover it.

**Comment by jacobkhan** [comment]
I want to have a tab on the settings page named styling where you can predefine various style setting such as options for text color, background color and button styles. I would like to be able to set them as ILIST property of name, color code( (#0f0f0f). When I create a hero block I would like to be able to use the properties set on the settings page for setting text color and so on. I dont want a full color picker but instead settings to make it that only an admin can access and change the text color options and so on. Does not need to be set in code by a developer
