### ISSUE TITLE
Find Index Prompt in Set Up Scripts

### ISSUE THREAD

**Issue by ngocnguyen-epi** [episerver/Foundation#460]
**Is your feature request related to a problem? Please describe.**
It would be great if we could configure Find indexes from the set up scripts. Maybe it could (optionally) prompt for the Service URL and Index?

<episerver.find serviceUrl="https://es-us-api01.episerver.com/9IKGqgMZaTD9KP4Op3ygsVB6JeJzR0N6" defaultIndex="episerverab_index55794" /> 

Or if it was really clever, for presales it could find a free index from a pool? Not sure how that would work.... but it would be handy!

**Comment by davidknipe** [comment]
Pre-sales should have their own Find indexes for demo use and also have access to FoundationBuilder that will swap the Find Url for them... Can we feed this back?

**Comment by ngocnguyen-epi** [comment]
@davidknipe Ok. Thanks!
