### ISSUE TITLE
Device and browser/OS support matrix

### ISSUE THREAD

**Issue by iamallyniam** [episerver/Foundation#473]
Due to the way that the javascript has been written and the build process implementation Foundation isn't working in Internet Explorer. Class syntax has been used, but not implemented with constructor or export. The build process isn't using compilers such as Browserify or Babel, so browsers not supporting Class can't run the code. There are also a variety of bugs (javascript console errors, styling inconsistencies) between Safari, Chrome, Opera and Firefox across Mac, Windows, iOS and Android in various OS versions.

A browser/os matrix is required to know what combinations of browsers and operating systems Foundation is compatible with and what contributors should be testing against when developing.

Taking data from the following sources, a table should be drawn up and agreed on what browsers and operating systems should be supported by Foundation.

- https://www.w3schools.com/browsers/default.asp
- https://www.w3counter.com/globalstats.php
- https://developer.android.com/about/dashboards
- https://developer.apple.com/support/app-store/

Levels of support could be defined depending on browser/operating system usage globally, taking into account the limitations of each browser or os. For older browsers that are still in use but only receiving security updates e.g. Internet Explorer, legacy Edge, small styling bugs maybe acceptable for a release but functional bugs that stop a user interacting with the site need to be fixed.

Depending on what's agree, there'll need to be code refactors for the front end considered, such as

- Introducing compilers that can convert ES6+ to ES5.
- Managing vendor dependencies through NPM
- Adjustment to build process to accommodate supported browsers in the autoprefixer options.
- Decoupling the build configuration from the build process.

**Comment by lunchin** [comment]
I agree, would you be open to having a meeting to discuss how we can achieve this.

**Comment by aj-gopal** [comment]
@lunchin Hey guys any updates on a possible solution for this issue? Is altering the gulpfile to run it through browserify and babelify a viable solution?

**Comment by lunchin** [comment]
This is now available as we webpack option output.ecmaVersion.  Please use version 6 from ie 11 support
