### ISSUE TITLE
A simple Google PageSpeed Gadget

### ISSUE THREAD

**Issue by ngocnguyen-epi** [episerver/Foundation#477]
**Is your feature request related to a problem? Please describe.**
Please create a gadget that I can add to the dashboard and the either side pane. The gadget should load up an iframe pointing to:
 
https://developers.google.com/speed/pagespeed/insights/?url=CURRENT_URL

Where CURRENT_URL is the external link to the page in the center pane.

**Comment by lunchin** [comment]
Moving to presales nuget package
