### ISSUE TITLE
Drag and drop image for partial view

### ISSUE THREAD

**Issue by thanhduc-epi** [episerver/Foundation#488]
**Is your feature request related to a problem? Please describe.**
Partial View Preview: Give the ability to drag and drop an image or video into the "Teaser Image" slot in a partial view. Would make this feature a LOT more useful.

**Comment by davidknipe** [comment]
Please note that it's no longer possible to edit the preview text, button text etc as a result of this change. Can we fix this please? 

See issue here: [](https://www.david-tec.com/global/media/bugvideos/pagepartialbug.mp4)
