### ISSUE TITLE
Can not download "win32-x64-72_binding.node"

### ISSUE THREAD

**Issue by YadhaviNava** [episerver/Foundation#624]
Finding the below error while running the setup file: kindly suggest solution if any. 

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-72_binding.node":
getaddrinfo ENOTFOUND github.com
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.
      export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
      npm config set proxy http://example.com:8080

**Comment by lunchin** [comment]
Can you delete the node_modules folder and try running setup again
