### ISSUE TITLE
Foundation site setup url is not working

### ISSUE THREAD

**Issue by ABackw** [episerver/Foundation#649]
**Describe the bug**
Step 5. in the foundation instructions (https://github.com/episerver/Foundation) says:

> When the installation is finished, a setup page is opened in your browser. If not, enter the URL http://yourdomainname/setup manually.

When you go to http://foundation/setup it gives you 404.

hosts file has both urls:
127.0.0.1 foundation
127.0.0.1 foundation-cm

**To Reproduce**
pull v2020.09.1 release, run setup enter site name "foundation" and hit enter on the rest of the questions. Wait until site installs and http://foundation is opened in browser.  Try to go http://foundation/setup 

**Expected behavior**
Expected behavior is that the step 7. dialog is opened "In the setup page under Import Content, select Remote Site File: Mosey and Remote Catalog File: Foundation_Fashion to import the Mosey demo site content. "

**Comment by ngocnguyen-epi** [comment]
@ABackw We removed the setup feature and set the site to default content (Mosey and Foundation_Fashion). And I'll update instructions soon.
