### ISSUE TITLE
Input validation on commerce checkout page not working

### ISSUE THREAD

**Issue by markprins81** [episerver/Foundation#688]
**Describe the bug**
The validation on the Commerce checkout page is not working. I'm able to place an order with a 'empty' shippingaddress.

**To Reproduce**
1. Add any product to the shopping cart
2. Click on Checkout
3. Select 'Ship to a new address'
4. Add a payment of type 'Cash on delivery'
4. Click 'Place Order'

**Expected behavior**
I would expect some validation to tell me that the shipping address is not correct, but the order is placed with an empty address.
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  88

**Comment by markprins81** [comment]
Am I correct to conclude that there is no client side validation anymore?

**Comment by tanvu-epi** [comment]
> Am I correct to conclude that there is no client side validation anymore?

Yes, you are. Do you want to add that?
