### ISSUE TITLE
Geta Categories not visible on Vistor Groups Site Criteria

### ISSUE THREAD

**Issue by sandervandepas** [episerver/Foundation#733]
Hi,

This lovely package was installed by using the Episerver Foundation package and now our customer wants to use Visitor Groups to display specific blocks on pages.
We saw there's an option below Site Criteria called Visited Geta Category, but when I open the dropdown by the Category property it is empty and has no categories, while there are a lot added on the site.

Is this a known issue or could you advice us how to fix this?
We don't see any console errors or something like that.

![image](https://user-images.githubusercontent.com/75935291/124632120-55b66c00-de84-11eb-8215-f583b028eb2c.png)

Thanks in advance!

Grtz Sander

**Comment by valdisiljuconoks** [comment]
Hey Sander,

Can you please file issue under Geta's repository for categories?

Thanks!

**Comment by ngocnguyen-epi** [comment]
Issued to Geta's repository
