### ISSUE TITLE
Mediachase.Commerce Version Issue

### ISSUE THREAD

**Issue by BenG-NS** [episerver/Foundation#748]
**Describe the bug**
After downloading the zip file from Github, running NuGet package restore, and running npm install to get the dependencies, building in Visual Studio 2019 results in the error below:

Error	CS1705	Assembly 'EPiServer.Tracking.Commerce' with identity 'EPiServer.Tracking.Commerce, Version=3.2.28.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' uses 'Mediachase.Commerce, Version=13.31.1.0, Culture=neutral, PublicKeyToken=6e58b501b34abce3' which has a higher version than referenced assembly 'Mediachase.Commerce' with identity 'Mediachase.Commerce, Version=13.31.0.0, Culture=neutral, PublicKeyToken=6e58b501b34abce3'

As far as I can tell from the instructions, you shouldn't need to build the Foundation project in Visual Studio at all.  (The instructions say you'll need Visual Studio, but the zip includes a script for building the project, and the steps never tell you to use VS.)  So I had tried just downloading the zip to a development server and following the instructions there, but that led to other errors.  So I downloaded the zip to my local machine, ran Restore NuGet Packages and npm install to get its dependencies, and tried building to see if I could find any build errors that I could fix.  That's when I ran into this error.

**To Reproduce**
1. Download the zip file from https://github.com/episerver/Foundation
2. Open the solution in Visual Studio.  Right click the solution and click Restore NuGet packages.
3. Open a command prompt and navigate to the src/Foundation folder.  Run "npm install" to install from Node's package manager.
4. In Visual Studio 2019, right click the solution and choose Rebuild Solution.  The error will appear in the Output window.

**Expected behavior**
Ideally, the project should build without errors.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Chrome: 93.0.4577.82 (Official Build) (64-bit)

**Comment by lunchin** [comment]
this should be fixed on master.  Just needed to upgrade the commerce version.  Thanks for repotinng

**Comment by hieuxinhe94** [comment]
> this should be fixed on master. Just needed to upgrade the commerce version. Thanks for repotinng

Let's verify before closing. This problem is still there.
