### ISSUE TITLE
Windows File Path Generated in macOS

### ISSUE THREAD

**Issue by joshuashafferopti** [episerver/Foundation#773]
**Describe the bug**
There seems to be a Windows-style file path generated by the project when running on OSX: `./src/Foundation/App_Data/Foundation\SearchIndex` 

The error generated when trying to run with this project structure is the following:
`/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(3177,5): error MSB3552: Resource file "**/*.resx" cannot be found.`

**To Reproduce**
1. Clone and install dependencies
2. Run `sql_server_optimizely` docker container
3. Run VS Solution

**Expected behavior**
The file path generated should be OS-agnostic. If not, documentation on the workaround should be provided.

**Desktop (please complete the following information):**
 - OS: 12.1 macOS
 - Browser: Chrome
 - Version: `main` branch of Foundation. Seems to be `v2021.10.1` based on tags.

**Comment by joshuashafferopti** [comment]
related `msbuild` thread: https://github.com/dotnet/msbuild/issues/406#issuecomment-353453937

**Comment by sl-mmuradov** [comment]
Encountered the same, yup.

**Comment by daniel-isaacs** [comment]
We have a possible fix, we'll be testing later today. @sl-mmuradov if you're able to test as well:

In appsettings.json, modify the paths for SearchIndex:

_"IndexerBasePath": "[appDataPath]/Foundation/SearchIndex"_
and
_"storage": "[appDataPath]/SearchIndex",_

**Comment by joshuashafferopti** [comment]
This issue was closed by #778
