### ISSUE TITLE
Default admin@example.com and store password don't work

### ISSUE THREAD

**Issue by wterpstra** [episerver/Foundation#774]
**Describe the bug**
The user `admin@example.com` and password `store` provided in the readme.md does not seem to work.

**To Reproduce**
1. Follow readme.md for clean installation
2. go to /episerver/cms
3. Login with `admin@example.com` and `store`
4. Check logs, see that password is invalid.  
```
2022-02-08 10:05:28.684 +01:00 [WRN] Invalid password for user.
```

**Expected behavior**
Password should be accepted

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 97.0.4692.99 (Official Build) (64-bit) (cohort: Stable)
 - Version: main branch:
```XML
<PackageReference Include="EPiServer.Commerce" Version="14.1.2" />
<PackageReference Include="EPiServer.CMS" Version="12.2.1" />
```

**Additional context**
In the end I was able to remove the password hash from the database and use the following code to set up a new password from the HomeController. When I provided the default `store` password it rejected it for being to short.

```C#
var user = await _userManager.Users.FirstOrDefaultAsync(x => x.UserName == "admin@example.com");
var result = await _userManager.AddPasswordAsync(user, "MyFancyStore123!");
```

**Comment by lunchin** [comment]
We will update the readme.md file to show the new default password

**Comment by wterpstra** [comment]
Ah shoot, I was looking at the master branch wile running main.

If this ever shows up in Google, this was on the main branch readme.md:
`Foundation has a default username and password of admin@example.com / Episerver123!`
