### ISSUE TITLE
Couldn't run the Foundation project successfully

### ISSUE THREAD

**Issue by burhansavci** [episerver/Foundation#795]
**Describe the bug**
When I try to run the latest project version, I get an error like the one below.

**To Reproduce**
1. Go to main [branch](https://github.com/episerver/Foundation/tree/main) 
2. Follow the steps in [README.md](https://github.com/episerver/Foundation/blob/main/README.md) in the below:
3. `open command prompt as administrator`
4.  `git clone https://github.com/episerver/Foundation.git`
5. `cd foundation`
6. `git checkout main`
7. `setup.cmd`
8. `dotnet run --project .\src\Foundation\Foundation.csproj` 
9. See the error below:

> Unhandled exception.
> EPiServer.Framework.Initialization.InitializationException: Initialize
> action failed for Initialize on class
> EPiServer.Data.DataInitialization, EPiServer.Data, Version=12.5.0.0,
> Culture=neutral, PublicKeyToken=8fe83dea738b45b7  --->
> System.Data.DataException: Failed to update database during execution
> of statement 'CREATE PROCEDURE [dbo].[mc_mcmd_TmpMetaFileMove]
>         @FileUid uniqueidentifier AS
>             SET NOCOUNT ON
>         INSERT INTO mcmd_MetaFile (FileUID, [FileName], Body)
>         SELECT FileUID, [FileName], Body FROM mcmd_TmpMetaFile WHERE FileUID=@FileUid
>         DELETE FROM mcmd_TmpMetaFile WHERE FileUID=@FileUID '  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Must declare the
> scalar variable "@FileUID".    at
> Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception,
> Boolean breakConnection, Action`1 wrapCloseInAction)    at
> Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject
> stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)    at
> Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior,
> SqlCommand cmdHandler, SqlDataReader dataStream,
> BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject
> stateObj, Boolean& dataReady)    at
> Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String
> methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)    at
> Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1
> completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache,
> Boolean asyncWrite, Boolean inRetry, String methodName)    at
> Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()    at
> EPiServer.Data.SchemaUpdates.Internal.ScriptRunnerImpl.<>c__DisplayClass5_0.<ExecuteScript>b__0()
> ClientConnectionId:a7d4f67f-cea1-4b37-b0bd-69af21d6e0ba Error
> Number:137,State:2,Class:15    --- End of inner exception stack trace
> ---    at EPiServer.Data.SchemaUpdates.Internal.ScriptRunnerImpl.<>c__DisplayClass5_0.<ExecuteScript>b__0()
> at
> EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.<>c__DisplayClass26_0`1.<ExecuteTransaction>b__0()
> at
> EPiServer.Data.SchemaUpdates.Internal.ScriptRunnerImpl.ExecuteScript(IDatabaseExecutor
> databaseHandler, StreamReader stream)    at
> EPiServer.Data.SchemaUpdates.Internal.ScriptRunnerImpl.<>c__DisplayClass2_0.<ExecuteScripts>b__0()
> at
> EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.<>c__DisplayClass25_0.<ExecuteTransaction>b__0()
> at
> EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.<>c__DisplayClass26_0`1.<ExecuteTransaction>b__0()
> at
> EPiServer.Data.Providers.SqlTransientErrorsRetryPolicy.Execute[TResult](Func`1
> method)    at
> EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.ExecuteTransaction[TResult](Func`1
> action)    at
> EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.ExecuteTransaction(Action
> action)    at
> EPiServer.Data.SchemaUpdates.Internal.ScriptRunnerImpl.ExecuteScripts(IDatabaseExecutor
> databaseHandler, IEnumerable`1 streams)    at
> EPiServer.Data.SchemaUpdates.Internal.ScriptExecutorImplementation.ExecuteEmbeddedZippedScripts(String
> connectionString, Assembly assembly, String resourcePath)    at
> EPiServer.Commerce.Internal.CommerceDatabaseSchemaUpdater.Update(ConnectionStringOptions
> connectionStringOptions)    at
> EPiServer.Data.SchemaUpdates.Internal.DatabaseSchemaManagerImplementation.EnsureDatabaseSchema(DataAccessOptions
> dataAccessOptions)    at
> EPiServer.Data.DataInitialization.ValidateDatabaseSchema(InitializationEngine
> context)    at
> EPiServer.Data.DataInitialization.Initialize(InitializationEngine
> context)    at
> EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass4_0.<Initialize>b__0()
> at
> EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action
> a, String key)    at
> EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine
> context)    at
> EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
> --- End of inner exception stack trace ---    at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
> at
> EPiServer.Framework.Initialization.InitializationEngine.ExecuteTransition(Boolean
> continueTransitions)    at
> EPiServer.Framework.Initialization.InitializationEngine.Initialize()  
> at
> EPiServer.Hosting.Internal.EPiServerFrameworkHost.StartAsync(CancellationToken
> cancellationToken)    at
> Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken
> cancellationToken)    at
> Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost
> host, CancellationToken token)    at
> Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost
> host, CancellationToken token)    at
> Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost
> host)    at Foundation.Program.Main(String[] args) in
> C:\Foundation\src\Foundation\Program.cs:line 24

**Expected behavior**
Successfully running the Foundation project

**Screenshots**
Console output:
![image](https://user-images.githubusercontent.com/51991915/162783807-2d518c38-5850-48b7-8ea0-50d61524b1c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - OS Version: 22000.556
 - SQL Server Version: Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22000: ) (Hypervisor)

**Comment by lunchin** [comment]
I am not able to recreate this.  What version of commerce is in the project file?

**Comment by burhansavci** [comment]
I just cloned the project and ran it from the main branch, so `EPiServer.Commerce` version is 14.2.1. You can look at my `Foundation.csproj` as shown below:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<VersionPrefix>2021.04.1.0</VersionPrefix>
		<VersionSuffix></VersionSuffix>
		<PackageVersion Condition=" '$(PackageVersion)' == '' ">$(VersionPrefix)$(VersionSuffix)</PackageVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Baaijte.Optimizely.ImageSharp.Web" Version="1.0.6" />
		<PackageReference Include="Boxed.AspNetCore.TagHelpers" Version="5.1.0" />
		<PackageReference Include="EPiServer.Commerce" Version="14.2.1" />
		<PackageReference Include="EPiServer.CMS" Version="12.4.0" />
		<PackageReference Include="EPiServer.CMS.AspNetCore.HtmlHelpers" Version="12.5.0" />
		<PackageReference Include="EPiServer.CMS.Core" Version="12.5.0" />
		<PackageReference Include="EPiServer.CMS.UI" Version="12.4.0" />
		<PackageReference Include="EPiServer.CMS.UI.Core" Version="12.4.0" />
		<PackageReference Include="EPiServer.ContentDefinitionsApi" Version="3.2.0" />
		<PackageReference Include="EPiServer.ContentDeliveryApi.Cms" Version="3.2.0" />
		<PackageReference Include="EPiServer.ContentManagementApi" Version="3.2.0" />
		<PackageReference Include="EPiServer.Framework" Version="12.5.0" />
		<PackageReference Include="EPiServer.Framework.AspNetCore" Version="12.5.0" />
		<PackageReference Include="EPiServer.Find.Cms" Version="14.0.4" />
		<PackageReference Include="EPiServer.Find.Commerce" Version="12.0.1" />
		<PackageReference Include="EPiServer.Forms" Version="5.1.0" />
		<PackageReference Include="EPiServer.Hosting" Version="12.5.0" />
		<PackageReference Include="EPiServer.Labs.ContentManager" Version="1.0.2" />
		<PackageReference Include="EPiServer.Marketing.Automation.Forms" Version="3.0.0" />
		<PackageReference Include="EPiServer.OpenIDConnect.UI" Version="3.2.0" />
		<PackageReference Include="EPiServer.PdfPreview" Version="2.0.0" />
		<PackageReference Include="EPiServer.Personalization.Commerce" Version="4.0.9" />
		<PackageReference Include="EPiServer.Telemetry.UI" Version="2.0.1" />
		<PackageReference Include="FileHelpers" Version="3.5.1" />
		<PackageReference Include="Geta.NotFoundHandler.Optimizely" Version="1.0.4" />
		<PackageReference Include="Jhoose.Security.Admin" Version="1.1.2.91" />
		<PackageReference Include="NonFactors.Grid.Core.Mvc6" Version="6.2.4" />
		<PackageReference Include="Powell.CouponCode" Version="1.0.3" />
		<PackageReference Include="Schema.NET" Version="11.0.1" />
		<PackageReference Include="Shorthand.ImageSharp.WebP" Version="2.2.1" />
		<PackageReference Include="SixLabors.ImageSharp.Web" Version="1.0.5" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
		<PackageReference Include="Wangkanai.Detection" Version="4.0.0" />
		<PackageReference Include="Serilog" Version="2.10.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="lang\**\*" />
		<None Update="App_Data\**" CopyToOutputDirectory="PreserveNewest" />
		<None Update="modules\_protected\Foundation\**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Features\Blocks\CommentsBlock\**" />
		<Compile Remove="Features\Blocks\FeedBlock\**" />
		<Compile Remove="Features\Blocks\GroupAdmissionBlock\**" />
		<Compile Remove="Features\Blocks\GroupCreationBlock\**" />
		<Compile Remove="Features\Blocks\LikeButtonBlock\**" />
		<Compile Remove="Features\Blocks\MembershipAffiliationBlock\**" />
		<Compile Remove="Features\Blocks\MembershipDisplayBlock\**" />
		<Compile Remove="Features\Blocks\RatingBlock\**" />
		<Compile Remove="Features\Blocks\SubscriptionBlock\**" />
		<Compile Remove="Features\Blog\BlogCommentBlock\**" />
		<Compile Remove="Features\Community\**" />
		<Compile Remove="Features\MultiShipment\**" />
		<Compile Remove="Infrastructure\Cms\Views\**" />
		<Compile Remove="Infrastructure\Commerce\Views\**" />
		<Compile Remove="Infrastructure\Kpi\**" />
		<Compile Remove="Infrastructure\Plugins\**" />
		<Compile Remove="Infrastructure\PowerSlices\**" />
		<Compile Remove="Infrastructure\Services\**" />
		<Compile Remove="Infrastructure\Social\**" />
		<Content Remove="Features\Blocks\CommentsBlock\**" />
		<Content Remove="Features\Blocks\FeedBlock\**" />
		<Content Remove="Features\Blocks\GroupAdmissionBlock\**" />
		<Content Remove="Features\Blocks\GroupCreationBlock\**" />
		<Content Remove="Features\Blocks\LikeButtonBlock\**" />
		<Content Remove="Features\Blocks\MembershipAffiliationBlock\**" />
		<Content Remove="Features\Blocks\MembershipDisplayBlock\**" />
		<Content Remove="Features\Blocks\RatingBlock\**" />
		<Content Remove="Features\Blocks\SubscriptionBlock\**" />
		<Content Remove="Features\Blog\BlogCommentBlock\**" />
		<Content Remove="Features\Community\**" />
		<Content Remove="Features\MultiShipment\**" />
		<Content Remove="Infrastructure\Kpi\**" />
		<Content Remove="Infrastructure\Plugins\**" />
		<Content Remove="Infrastructure\PowerSlices\**" />
		<Content Remove="Infrastructure\Social\**" />
		<EmbeddedResource Remove="Features\Blocks\CommentsBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\FeedBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\GroupAdmissionBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\GroupCreationBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\LikeButtonBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\MembershipAffiliationBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\MembershipDisplayBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\RatingBlock\**" />
		<EmbeddedResource Remove="Features\Blocks\SubscriptionBlock\**" />
		<EmbeddedResource Remove="Features\Blog\BlogCommentBlock\**" />
		<EmbeddedResource Remove="Features\Community\**" />
		<EmbeddedResource Remove="Features\MultiShipment\**" />
		<EmbeddedResource Remove="Infrastructure\Kpi\**" />
		<EmbeddedResource Remove="Infrastructure\Plugins\**" />
		<EmbeddedResource Remove="Infrastructure\PowerSlices\**" />
		<EmbeddedResource Remove="Infrastructure\Social\**" />
		<None Remove="Features\Blocks\CommentsBlock\**" />
		<None Remove="Features\Blocks\FeedBlock\**" />
		<None Remove="Features\Blocks\GroupAdmissionBlock\**" />
		<None Remove="Features\Blocks\GroupCreationBlock\**" />
		<None Remove="Features\Blocks\LikeButtonBlock\**" />
		<None Remove="Features\Blocks\MembershipAffiliationBlock\**" />
		<None Remove="Features\Blocks\MembershipDisplayBlock\**" />
		<None Remove="Features\Blocks\RatingBlock\**" />
		<None Remove="Features\Blocks\SubscriptionBlock\**" />
		<None Remove="Features\Blog\BlogCommentBlock\**" />
		<None Remove="Features\Community\**" />
		<None Remove="Features\MultiShipment\**" />
		<None Remove="Infrastructure\Kpi\**" />
		<None Remove="Infrastructure\Plugins\**" />
		<None Remove="Infrastructure\PowerSlices\**" />
		<None Remove="Infrastructure\Social\**" />
		<Compile Remove="Infrastructure\Cms\Extensions\IAppBuilderExtensions.cs" />
		<Compile Remove="Infrastructure\Commerce\Markets\AJAXLocalizationFilterAttribute.cs" />
		<Compile Remove="Infrastructure\Display\FoundationDisplayModeProvider.cs" />
		<Folder Include="wwwroot\" />
		<None Include="Features\Shared\Components\Dropdown\Default.cshtml" />
		<None Include="Features\Shared\Components\Money\Default.cshtml" />
	</ItemGroup>
</Project>
```

**Comment by lunchin** [comment]
Yeah there was an issue with 14.2.0 which I thought could have caused the issue. Where is your sql server little confused in your initial post. What does your connectionstring look like.

**Comment by burhansavci** [comment]
My local DB connection string looks like this:

```
  "ConnectionStrings": {
    "EPiServerDB": "Server=.;Database=brhn-epi-tst-app-local-db.Cms;User Id=brhn-epi-tst-app-local-db.CmsUser;Password=IRemovedMyActualPwdHere;MultipleActiveResultSets=True",
    "EcfSqlConnection": "Server=.;Database=brhn-epi-tst-app-local-db.Commerce;User Id=brhn-epi-tst-app-local-db.CmsUser;Password=IRemovedMyActualPwdHere;"
  },
```
For testing, I ran the SQL Server from Docker. After that, the problem seems to be solved. I assume it is solved because I updated the SQL version from 15.0.2080.9 to 15.0.4178.1. However, another problem occurred as shown below:

```
2022-04-18 12:38:18.494 +03:00 [ERR] Initialize action failed for 'Initialize on class Foundation.Infrastructure.InitializeSite, Foundation, Version=2021.4.1.0, Culture=neutral, PublicKeyToken=null'
Microsoft.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'FoundationConfiguration_List'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at Foundation.Infrastructure.Commerce.Install.InstallService.GetFoundationConfiguration() in C:\Foundation\src\Foundation\Infrastructure\Commerce\Install\InstallService.cs:line 108
   at Foundation.Infrastructure.Commerce.Install.InstallService.get_FoundationConfiguration() in C:\Foundation\src\Foundation\Infrastructure\Commerce\Install\InstallService.cs:line 36
   at Foundation.Infrastructure.Commerce.Install.InstallService.ShouldInstall() in C:\Foundation\src\Foundation\Infrastructure\Commerce\Install\InstallService.cs:line 72
   at Foundation.Infrastructure.Commerce.Extensions.InitializationEngineExtensions.InitializeFoundationCommerce(InitializationEngine context) in C:\Foundation\src\Foundation\Infrastructure\Commerce\Extensions\InitializationEngineExtensions.cs:line 26
   at Foundation.Infrastructure.InitializeSite.Initialize(InitializationEngine context) in C:\Foundation\src\Foundation\Infrastructure\InitializeSite.cs:line 181
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
ClientConnectionId:ed58d064-cb4d-4314-bfc1-1f52d7038266
Error Number:2812,State:62,Class:16
```
 
Connection strings for SQL server run from docker instance:
```
  "ConnectionStrings": {
    "EPiServerDB": "Server=localhost,1434;Database=brhn-epi-tst-app-docker-db.Cms;User Id=brhn-epi-tst-app.CmsUser;Password=whA^7RNDKYaB&Oc$g^TosjL5L;MultipleActiveResultSets=True",
    "EcfSqlConnection": "Server=localhost,1434;Database=brhn-epi-tst-app-docker-db.Commerce;User Id=brhn-epi-tst-app.CmsUser;Password=whA^7RNDKYaB&Oc$g^TosjL5L;"
  },
```

My docker instance SQL server version:
Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) - 15.0.4178.1 (X64)   Sep 23 2021 16:47:49   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Linux (Ubuntu 20.04.3 LTS) <X64>

**Comment by lunchin** [comment]
Somehow one the foundation scripts did not get run when running setup.cmd. Can you manually run the following scripts
`echo ## Installing foundation configuration ##
%sql% -d %commerce_db% -b -i "Build\SqlScripts\FoundationConfigurationSchema.sql" -v appname=%APPNAME% 

echo ## Installing unique coupon schema ##
%sql% -d %commerce_db% -b -i "Build\SqlScripts\UniqueCouponSchema.sql"
`

**Comment by burhansavci** [comment]
After manually running the scripts you mentioned, I was able to successfully launch the project. Thanks a lot!
