### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by marisks** [episerver/Foundation#798]
.NET 5 is going to expire on the 8th of May: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
When Foundation and Optimizely (Episerver) will make .NET 6 the default framework version?

**Comment by lunchin** [comment]
we should be able to update to 6 once the commerce packages are out which I expect next week on  the feed.

**Comment by rw-kaber** [comment]
Hi @lunchin, any updates in terms of release timeline for Commerce packages?

**Comment by lunchin** [comment]
Sorry it has been in testing for a couple weeks because of a new search feature that in the release as well.  Things now look on track for Tuesday release.

**Comment by rw-kaber** [comment]
Hey @lunchin, it seems that Commerce didn't make it to yesterday's release - any updates for revised timeline?

**Comment by marisks** [comment]
I see that .NET 6 packages are released now. When could we have Foundation updated?

**Comment by rw-kaber** [comment]
@marisks From what I can see, this is no longer the case, the Commerce package has been recalled and the .NET 6 version is no longer available.
https://world.optimizely.com/blogs/Erik-Skagerlind/Dates/2022/5/commerce-14-3-0-has-temporarily-been-removed-from-the-optimizely-nuget-feed/

Also, the Foundation project has dependency on `EPiServer.Find.Cms` package, which also lacks the .NET 6 version
https://nuget.optimizely.com/package/?id=EPiServer.Find.Cms

@lunchin Do you have any updates to share?

**Comment by lunchin** [comment]
The solution is now targeting 6.
