### ISSUE TITLE
DisplayResolution name localization is cached and will always display in the first loaded locale

### ISSUE THREAD

**Issue by wterpstra** [episerver/Foundation#815]
**Describe the bug**
When I change UI language in the CMS the display resolution name remains in the language it was first loaded in. The value is cached inside the `DisplayResolutionBase.Name` property.

**To Reproduce**
1. Add a translation for the resolutions inside the `src/Foundation/lang/Display_EN.xml` localization file.
2. Start foundation, log in.
3. In the CMS page editor, see the resolution name are in language A (probably english)
4. Change the UI language to language B.
5. Go back to see the resolution name did not change to language B and remains language A.

**Expected behavior**
Resolution names should be localizable

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 101

**Comment by lunchin** [comment]
Merged, thanks for the PR!
